modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="veylith"
version="1.0.0"
displayName="The Veylith"
authors="Clara Blair"
description='''The Veylith is a dark-fantasy horror expansion for Minecraft.'''
displayTest="MATCH_VERSION"

[[dependencies.veylith]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.veylith]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
